[project]
name = "little-book-of-linalg"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.7",
    "numpy>=2.3.3",
    "scipy>=1.16.2",
    "ipympl (>=0.9.8,<0.10.0)",
    "sympy (>=1.14.0,<2.0.0)",
]
